CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y

CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=1800000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

CONFIG_ZMK_POINTING=y

CONFIG_ZMK_EXT_POWER=y

# PMW3610 driver (badjeff)
CONFIG_PMW3610_ALT=y
# CONFIG_PMW3610_ALT_REPORT_INTERVAL_MIN=12

# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
