CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_MOUSE=y

CONFIG_ZMK_POINTING=y

CONFIG_ZMK_EXT_POWER=y

# Enable USB for ZMK Studio
CONFIG_ZMK_USB=y

# Split keyboard battery reporting
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_QUEUE_SIZE=5

# PMW3610 driver (badjeff)
CONFIG_PMW3610_ALT=y
# CONFIG_PMW3610_ALT_REPORT_INTERVAL_MIN=12

# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
